import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// voucher: the voucher object (with ledger_name, voucher_type, etc.)
// items: array of voucher_items (with item_name, quantity, rate, amount)
// companyName: the active company's name, shown as the "from" business
export function generateInvoicePDF(voucher, items, companyName) {
  const doc = new jsPDF();

  // --- Header ---
  doc.setFontSize(20);
  doc.setFont(undefined, "bold");
  doc.text(companyName, 14, 20);

  doc.setFontSize(11);
  doc.setFont(undefined, "normal");
  doc.text(
    voucher.voucher_type === "purchase" ? "PURCHASE INVOICE" : "SALES INVOICE",
    14,
    28
  );

  // --- Voucher info (right-aligned block) ---
  doc.setFontSize(10);
  doc.text(`Invoice #: ${voucher.id}`, 150, 20);
  doc.text(`Date: ${new Date(voucher.voucher_date).toLocaleDateString()}`, 150, 26);

  // --- Party details ---
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.text(
    voucher.voucher_type === "purchase" ? "Supplier:" : "Customer:",
    14,
    40
  );
  doc.setFont(undefined, "normal");
  doc.text(voucher.ledger_name, 14, 46);

  // --- Line items table ---
  const tableRows = items.map((item) => [
    item.item_name,
    item.unit,
    item.quantity,
    `Rs. ${parseFloat(item.rate).toFixed(2)}`,
    `Rs. ${parseFloat(item.amount).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 55,
    head: [["Item", "Unit", "Qty", "Rate", "Amount"]],
    body: tableRows,
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235] }, // blue header, matches the app's blue theme
  });

  // --- Totals section, placed right after the table ends ---
  const finalY = doc.lastAutoTable.finalY + 10;

  doc.setFontSize(10);
  doc.text(`Items Total:`, 140, finalY);
  doc.text(`Rs. ${parseFloat(voucher.total_amount).toFixed(2)}`, 180, finalY, { align: "right" });

  let currentY = finalY;

  if (parseFloat(voucher.gst_percent) > 0) {
    const halfGst = parseFloat(voucher.gst_amount) / 2;
    const halfPercent = parseFloat(voucher.gst_percent) / 2;

    currentY += 6;
    doc.text(`CGST (${halfPercent.toFixed(2)}%):`, 140, currentY);
    doc.text(`Rs. ${halfGst.toFixed(2)}`, 180, currentY, { align: "right" });

    currentY += 6;
    doc.text(`SGST (${halfPercent.toFixed(2)}%):`, 140, currentY);
    doc.text(`Rs. ${halfGst.toFixed(2)}`, 180, currentY, { align: "right" });
  }

  currentY += 8;
  doc.setFont(undefined, "bold");
  doc.setFontSize(12);
  doc.text(`Grand Total:`, 140, currentY);
  doc.text(`Rs. ${parseFloat(voucher.grand_total).toFixed(2)}`, 180, currentY, { align: "right" });

  // --- Footer note ---
  doc.setFontSize(9);
  doc.setFont(undefined, "normal");
  doc.text("Generated by SmartERP", 14, 285);

  // Triggers an actual browser download of the generated PDF
  doc.save(`Invoice-${voucher.id}.pdf`);
}